# SPDX-License-Identifier: MPL-2.0
# Copyright 2024-2026 Pablo P.C.
"""Intrinsical Policy Engine package metadata."""

from intrinsical_policy_engine.api import (
    AssessmentRequest,
    AssessmentResult,
    Diagnostic,
    DiagnosticSeverity,
    Engine,
    EngineConfig,
    ExecutionPolicy,
    ExportRequest,
    ExportResult,
    GateCheck,
    GateDecision,
    GateReport,
    GateStatus,
    PackCompatibilityError,
    PackCompatibilityMetadataError,
    PackDescriptor,
    PackError,
    PackLicenseMetadataError,
    PackMetadataError,
    PackProvider,
    PackValidationRequest,
    PackValidationResult,
    ProductIdentity,
    SealRequest,
    SealResult,
    evaluate_gate,
)
from intrinsical_policy_engine.common.constants import CANONICAL_ENGINE_VERSION

__all__ = [
    "AssessmentRequest",
    "AssessmentResult",
    "Diagnostic",
    "DiagnosticSeverity",
    "Engine",
    "EngineConfig",
    "ExecutionPolicy",
    "ExportRequest",
    "ExportResult",
    "GateCheck",
    "GateDecision",
    "GateReport",
    "GateStatus",
    "PackCompatibilityError",
    "PackCompatibilityMetadataError",
    "PackDescriptor",
    "PackError",
    "PackLicenseMetadataError",
    "PackMetadataError",
    "PackProvider",
    "PackValidationRequest",
    "PackValidationResult",
    "ProductIdentity",
    "SealRequest",
    "SealResult",
    "__version__",
    "evaluate_gate",
]
__version__ = CANONICAL_ENGINE_VERSION
