# SPDX-License-Identifier: MPL-2.0
# Copyright 2024-2026 Pablo P.C.
"""Base classes for export strategies.

Architectural invariant:
- ExportContext is an ADAPTER-layer construct (infrastructure)
- EvalContext is a DOMAIN-layer construct (business logic)
- ExportContext COMPOSES EvalContext, never the reverse
- Strategies return ArtifactsDelta; orchestrator aggregates (P2 Refactor)
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from intrinsical_policy_engine.adapters.export.filesystem.filesystem_exporter import (
        FilesystemExporter,
    )
    from intrinsical_policy_engine.app.rendering.templating import ArtifactAssembler
    from intrinsical_policy_engine.domain.bundles.context import EvalContext
    from intrinsical_policy_engine.domain.types import Plan


@dataclass(frozen=True)
class ArtifactsDelta:
    """Immutable result from a strategy execution.

    Strategies return this instead of mutating ExportContext directly.
    The orchestrator aggregates deltas into the context.

    Attributes:
        generated_files: Files created by this strategy
        metrics: Metrics computed by this strategy (e.g., coverage stats)
        eval_ctx: Optional EvalContext built by the strategy (for downstream use)
    """

    generated_files: tuple[Path, ...] = ()
    metrics: dict[str, Any] = field(default_factory=dict)
    eval_ctx: Any = None  # EvalContext | None, using Any to avoid forward ref issues

    @classmethod
    def empty(cls) -> ArtifactsDelta:
        """Create an empty delta (no-op result).

        Returns:
            ArtifactsDelta with no files, empty metrics, and no eval_ctx.
        """
        return cls()

    @classmethod
    def from_files(cls, files: list[Path]) -> ArtifactsDelta:
        """Create a delta from a list of generated files.

        Args:
            files: List of file paths generated by the strategy.

        Returns:
            ArtifactsDelta containing only the generated files.
        """
        return cls(generated_files=tuple(files))

    def merge(self, other: ArtifactsDelta) -> ArtifactsDelta:
        """Merge two deltas into one (immutable).

        Combines files, metrics, and eval_ctx from both deltas.
        Metrics are merged (other takes precedence for conflicts).
        Eval_ctx prefers other if present.

        Args:
            other: Another ArtifactsDelta to merge with.

        Returns:
            New ArtifactsDelta with merged content.
        """
        merged_files = self.generated_files + other.generated_files
        merged_metrics = {**self.metrics, **other.metrics}
        # Prefer the newer eval_ctx if present
        merged_eval_ctx = other.eval_ctx if other.eval_ctx is not None else self.eval_ctx
        return ArtifactsDelta(
            generated_files=merged_files,
            metrics=merged_metrics,
            eval_ctx=merged_eval_ctx,
        )


@dataclass
class ExportContext:
    """Adapter-layer context for the export pipeline.

    Composes domain EvalContext with infrastructure concerns.
    Domain data flows in; infrastructure state accumulates.

    Note: strategies should avoid mutating this directly.
    Instead, they return ArtifactsDelta and the orchestrator updates the context.

    Attributes:
        plan: The compliance plan being exported
        ctx: Jinja template context (enriched step-by-step)
        eval_ctx: Domain evaluation context (optional, for bundle predicates)
        out_dir: Output directory path
        templates_dir: Templates directory path
        assembler: Jinja template assembler
        config: Export configuration dict
        strict: Whether strict mode is enabled
        generated_files: Accumulator for fingerprinting
        metrics: Explicit mutation target for evidence/coverage metrics
    """

    plan: Plan
    ctx: dict[str, Any]
    out_dir: Path
    templates_dir: Path
    assembler: ArtifactAssembler
    config: dict[str, Any]
    strict: bool

    # Optional domain context (for bundle predicates)
    eval_ctx: EvalContext | None = None

    # Mutable pipeline state - explicit targets for mutation
    generated_files: list[Path] = field(default_factory=list)
    metrics: dict[str, Any] = field(default_factory=dict)

    def apply_delta(self, delta: ArtifactsDelta) -> None:
        """Apply an ArtifactsDelta to this context (mutation).

        This is the ONLY sanctioned way to update the context from strategies.
        Called by the orchestrator after each strategy execution.

        Args:
            delta: ArtifactsDelta to apply. Files are appended, metrics are updated,
                and eval_ctx is replaced if present in delta.
        """
        self.generated_files.extend(delta.generated_files)
        self.metrics.update(delta.metrics)
        if delta.eval_ctx is not None:
            self.eval_ctx = delta.eval_ctx


class ExportStrategy(ABC):
    """Interface for export pipeline steps.

    Each strategy is responsible for a cohesive subset of export logic.
    Strategies receive the parent exporter for access to helpers (logging,
    file writing, etc.) and the shared ExportContext for READ-ONLY access.

    CRITICAL: Strategies MUST return ArtifactsDelta instead of
    mutating ExportContext directly. The orchestrator applies the delta.
    """

    @abstractmethod
    def execute(self, exporter: FilesystemExporter, context: ExportContext) -> ArtifactsDelta:
        """Execute the strategy logic.

        Args:
            exporter: Parent exporter instance (for helpers and logging)
            context: Shared export context (READ access preferred)

        Returns:
            ArtifactsDelta containing generated files and metrics from this step.

        Raises:
            ValueError: If strict mode is enabled and validation fails
        """
        pass
