# SPDX-License-Identifier: MPL-2.0
# Copyright 2024-2026 Pablo P.C.
"""Characterization and target contracts for the 3.0 Python package move."""

from __future__ import annotations

import ast
import importlib
import os
import re
import subprocess
import sys
import tarfile
import tomllib
import zipfile
from email.parser import Parser
from pathlib import Path, PurePosixPath

import pytest

ROOT = Path(__file__).resolve().parents[2]
PYPROJECT_PATH = ROOT / "pyproject.toml"
SOURCE_ROOT = ROOT / "src"
CANONICAL_PACKAGE_ROOT = SOURCE_ROOT / "intrinsical_policy_engine"
TARGET_WHEEL = os.getenv("IPE_3_0_WHEEL")
TARGET_SDIST = os.getenv("IPE_3_0_SDIST")
BASELINE_2X_MODULES = 172
BASELINE_2X_PACKAGE_INITIALIZERS = 45
BASELINE_2X_RUNTIME_LEGACY_IMPORTS = 436

requires_wheel_3 = pytest.mark.skipif(
    not TARGET_WHEEL,
    reason="3.0 wheel contract; provide IPE_3_0_WHEEL=/path/to/wheel",
)
requires_sdist_3 = pytest.mark.skipif(
    not TARGET_SDIST,
    reason="3.0 sdist contract; provide IPE_3_0_SDIST=/path/to/sdist",
)

SDIST_RELEASE_FILES = {
    "BOUNDARIES.md",
    "CHANGELOG.md",
    "LICENSE",
    "MANIFEST.in",
    "NOTICE",
    "PKG-INFO",
    "PROVENANCE.md",
    "README.md",
    "SECURITY.md",
    "pyproject.toml",
    # Generated by setuptools while assembling the source distribution.
    "setup.cfg",
}
SDIST_FORBIDDEN_ROOTS = {
    "demos",
    "frameworks",
    "private",
    "scripts",
    "tests",
    "workspace",
}
SDIST_FORBIDDEN_CANONICAL_COMPONENTS = {"private", "workspace"}
MARKDOWN_LINK = re.compile(r"\[[^]]+\]\(([^)]+)\)")


def _pyproject() -> dict:
    return tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))


def _entrypoint() -> str:
    return str(_pyproject()["project"]["scripts"]["ipe"])


def _python_files(*roots: Path) -> list[Path]:
    return sorted(path for root in roots if root.exists() for path in root.rglob("*.py"))


def _absolute_imports_with_prefix(paths: list[Path], prefix: str) -> list[str]:
    found: list[str] = []
    for path in paths:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom):
                module = node.module or ""
                if module == prefix or module.startswith(prefix + "."):
                    found.append(f"{path.relative_to(ROOT)}:{node.lineno}:{module}")
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name == prefix or alias.name.startswith(prefix + "."):
                        found.append(f"{path.relative_to(ROOT)}:{node.lineno}:{alias.name}")
    return found


def _require_2x_layout() -> None:
    if CANONICAL_PACKAGE_ROOT.exists():
        pytest.skip("2.x baseline no longer applies after the namespace move")


def test_2x_baseline_version_and_entrypoint_are_coherent() -> None:
    """Freeze the released baseline until the atomic namespace batch lands."""
    _require_2x_layout()
    config = _pyproject()
    project = config["project"]
    package_find = config["tool"]["setuptools"]["packages"]["find"]
    runtime_package = importlib.import_module("src")
    module_name, function_name = _entrypoint().split(":", maxsplit=1)
    main_module = importlib.import_module(module_name)

    assert project["name"] == "intrinsical-policy-engine"
    assert project["version"] == runtime_package.__version__
    assert _entrypoint() == "intrinsical_policy_engine.app.cli.main:main"
    assert package_find == {
        "where": ["."],
        "include": ["src*", "scripts*"],
        "namespaces": False,
    }
    assert callable(getattr(main_module, function_name))


def test_2x_baseline_module_cli_reports_distribution_version() -> None:
    _require_2x_layout()
    version = str(_pyproject()["project"]["version"])
    completed = subprocess.run(
        [sys.executable, "-m", "intrinsical_policy_engine.app.cli", "--version"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout.strip() == f"ipe {version}"


def test_2x_baseline_namespace_inventory_is_frozen() -> None:
    """Make a changed migration surface visible during the preparation phase."""
    _require_2x_layout()
    source_files = _python_files(SOURCE_ROOT)
    legacy_imports = _absolute_imports_with_prefix(source_files, "src")

    assert len(source_files) >= BASELINE_2X_MODULES
    assert len(list(SOURCE_ROOT.rglob("__init__.py"))) >= BASELINE_2X_PACKAGE_INITIALIZERS
    assert 0 < len(legacy_imports) <= BASELINE_2X_RUNTIME_LEGACY_IMPORTS


def test_3x_uses_true_src_layout_and_canonical_entrypoint() -> None:
    config = _pyproject()
    package_find = config["tool"]["setuptools"]["packages"]["find"]

    assert config["build-system"]["requires"] == ["setuptools>=77.0.3"]
    assert CANONICAL_PACKAGE_ROOT.is_dir()
    assert (CANONICAL_PACKAGE_ROOT / "__init__.py").is_file()
    assert (CANONICAL_PACKAGE_ROOT / "__main__.py").is_file()
    assert not (SOURCE_ROOT / "__init__.py").exists()
    assert package_find["where"] == ["src"]
    assert package_find["include"] == ["intrinsical_policy_engine*"]
    assert package_find["namespaces"] is False
    assert config["tool"]["setuptools"]["package-data"] == {
        "intrinsical_policy_engine": ["py.typed"]
    }
    assert _entrypoint() == "intrinsical_policy_engine.app.cli.main:main"


def test_3x_source_tests_and_scripts_have_no_legacy_imports() -> None:
    paths = _python_files(CANONICAL_PACKAGE_ROOT, ROOT / "tests", ROOT / "scripts")
    assert _absolute_imports_with_prefix(paths, "src") == []


def test_3x_runtime_does_not_import_repository_scripts() -> None:
    paths = _python_files(CANONICAL_PACKAGE_ROOT)
    assert _absolute_imports_with_prefix(paths, "scripts") == []


def test_3x_module_cli_reports_distribution_version() -> None:
    version = str(_pyproject()["project"]["version"])
    completed = subprocess.run(
        [sys.executable, "-m", "intrinsical_policy_engine", "--version"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout.strip() == f"ipe {version}"


@requires_wheel_3
def test_3x_wheel_contains_only_the_canonical_runtime_package() -> None:
    wheel = Path(str(TARGET_WHEEL)).expanduser().resolve()
    assert wheel.is_file(), f"IPE_3_0_WHEEL does not exist: {wheel}"

    with zipfile.ZipFile(wheel) as archive:
        names = set(archive.namelist())
        metadata_name = next(name for name in names if name.endswith(".dist-info/METADATA"))
        entry_points_name = next(
            name for name in names if name.endswith(".dist-info/entry_points.txt")
        )
        top_level_name = next(name for name in names if name.endswith(".dist-info/top_level.txt"))
        metadata = Parser().parsestr(archive.read(metadata_name).decode("utf-8"))
        entry_points = archive.read(entry_points_name).decode("utf-8")
        top_levels = {
            line.strip()
            for line in archive.read(top_level_name).decode("utf-8").splitlines()
            if line.strip()
        }

    assert metadata["Name"] == "intrinsical-policy-engine"
    assert metadata["Version"] == str(_pyproject()["project"]["version"])
    assert top_levels == {"intrinsical_policy_engine"}
    assert "ipe = intrinsical_policy_engine.app.cli.main:main" in entry_points
    assert "intrinsical_policy_engine/__init__.py" in names
    assert "intrinsical_policy_engine/__main__.py" in names
    assert "intrinsical_policy_engine/py.typed" in names
    assert not any(name.startswith(("src/", "scripts/", "tests/", "demos/")) for name in names)
    assert not any(".codex" in Path(name).parts for name in names)


@requires_sdist_3
def test_3x_sdist_contains_only_public_release_sources() -> None:
    sdist = Path(str(TARGET_SDIST)).expanduser().resolve()
    assert sdist.is_file(), f"IPE_3_0_SDIST does not exist: {sdist}"

    config = _pyproject()["project"]
    expected_version = str(config["version"])
    expected_root = f"intrinsical_policy_engine-{expected_version}"
    invalid_paths: list[str] = []

    with tarfile.open(sdist, mode="r:*") as archive:
        members = archive.getmembers()
        roots = {
            PurePosixPath(member.name).parts[0]
            for member in members
            if PurePosixPath(member.name).parts
        }
        assert roots == {expected_root}
        assert all(member.isfile() or member.isdir() for member in members)

        for member in members:
            archive_path = PurePosixPath(member.name)
            parts = archive_path.parts
            assert not archive_path.is_absolute()
            assert ".." not in parts
            relative_parts = parts[1:]
            if not relative_parts:
                continue

            first = relative_parts[0]
            if first.casefold() in SDIST_FORBIDDEN_ROOTS:
                invalid_paths.append(member.name)
                continue

            if len(relative_parts) == 1 and first in SDIST_RELEASE_FILES:
                continue
            if first == "docs":
                continue
            if first == "src":
                if len(relative_parts) == 1:
                    continue
                source_root = relative_parts[1]
                if source_root == "intrinsical_policy_engine.egg-info":
                    continue
                if source_root == "intrinsical_policy_engine" and not (
                    {part.casefold() for part in relative_parts[2:]}
                    & SDIST_FORBIDDEN_CANONICAL_COMPONENTS
                ):
                    continue
            invalid_paths.append(member.name)

        pkg_info_member = next(
            member
            for member in members
            if PurePosixPath(member.name) == PurePosixPath(expected_root, "PKG-INFO")
        )
        pkg_info_file = archive.extractfile(pkg_info_member)
        assert pkg_info_file is not None
        pkg_info = Parser().parsestr(pkg_info_file.read().decode("utf-8"))
        readme_file = archive.extractfile(f"{expected_root}/README.md")
        assert readme_file is not None
        readme = readme_file.read().decode("utf-8")

    archived_files = {
        PurePosixPath(*PurePosixPath(member.name).parts[1:]).as_posix()
        for member in members
        if member.isfile()
    }
    local_readme_links = {
        target.split("#", maxsplit=1)[0]
        for target in MARKDOWN_LINK.findall(readme)
        if target and not target.startswith(("#", "http://", "https://", "mailto:"))
    }

    assert invalid_paths == []
    assert pkg_info["Name"] == str(config["name"])
    assert pkg_info["Version"] == expected_version
    assert local_readme_links <= archived_files
